"""
Alias dictionaries for normalizing Bulgarian real estate data.

These mappings convert various text formats (Bulgarian, transliterated, API values)
to standardized enum values for offer types, property types, cities, currencies,
and neighborhoods.
"""

from src.core.enums import (
    City,
    Currency,
    OfferType,
    PlovdivNeighborhood,
    PropertyType,
    SofiaNeighborhood,
)

OFFER_TYPE_ALIASES: dict[str, OfferType] = {
    # Bulgarian text
    "продава": OfferType.SALE,
    "продажба": OfferType.SALE,
    "продаван": OfferType.SALE,
    "за продажба": OfferType.SALE,
    "продажби": OfferType.SALE,
    "наем": OfferType.RENT,
    "под наем": OfferType.RENT,
    "дава под наем": OfferType.RENT,
    "наеми": OfferType.RENT,
    # URL patterns (transliterated)
    "prodava": OfferType.SALE,
    "prodajba": OfferType.SALE,
    "prodazhba": OfferType.SALE,
    "prodazhbi": OfferType.SALE,
    "prodajbi": OfferType.SALE,
    "naem": OfferType.RENT,
    "pod-naem": OfferType.RENT,
    "dava-pod-naem": OfferType.RENT,
    "naemi": OfferType.RENT,
    # API values
    "sell": OfferType.SALE,
    "apartmentsell": OfferType.SALE,
    "housesell": OfferType.SALE,
    "landsell": OfferType.SALE,
    "landagro": OfferType.SALE,
    "rent": OfferType.RENT,
    "apartmentrent": OfferType.RENT,
    "houserent": OfferType.RENT,
}

PROPERTY_TYPE_ALIASES: dict[str, PropertyType] = {
    # Bulgarian text
    "студио": PropertyType.STUDIO,
    "едностаен": PropertyType.ONE_ROOM,
    "1-стаен": PropertyType.ONE_ROOM,
    "1 стаен": PropertyType.ONE_ROOM,
    "двустаен": PropertyType.TWO_ROOM,
    "2-стаен": PropertyType.TWO_ROOM,
    "2 стаен": PropertyType.TWO_ROOM,
    "тристаен": PropertyType.THREE_ROOM,
    "3-стаен": PropertyType.THREE_ROOM,
    "3 стаен": PropertyType.THREE_ROOM,
    "четиристаен": PropertyType.FOUR_ROOM,
    "4-стаен": PropertyType.FOUR_ROOM,
    "4 стаен": PropertyType.FOUR_ROOM,
    "многостаен": PropertyType.MULTI_ROOM,
    "5-стаен": PropertyType.MULTI_ROOM,
    "5 стаен": PropertyType.MULTI_ROOM,
    "мезонет": PropertyType.MAISONETTE,
    "мезонети": PropertyType.MAISONETTE,
    "земя": PropertyType.LAND,
    "земеделска": PropertyType.LAND,
    "земеделска земя": PropertyType.LAND,
    "парцел": PropertyType.LAND,
    "къща": PropertyType.HOUSE,
    "вила": PropertyType.HOUSE,
    "офис": PropertyType.OFFICE,
    "ателие": PropertyType.STUDIO_APARTMENT,
    "гараж": PropertyType.GARAGE,
    "паркомясто": PropertyType.PARKING,
    # URL patterns (transliterated)
    "studio": PropertyType.STUDIO,
    "ednostaen": PropertyType.ONE_ROOM,
    "ednostayn": PropertyType.ONE_ROOM,
    "ednostayni": PropertyType.ONE_ROOM,
    "dvustaen": PropertyType.TWO_ROOM,
    "dvustayn": PropertyType.TWO_ROOM,
    "dvustayni": PropertyType.TWO_ROOM,
    "dvustaini": PropertyType.TWO_ROOM,
    "tristaen": PropertyType.THREE_ROOM,
    "tristayn": PropertyType.THREE_ROOM,
    "tristayni": PropertyType.THREE_ROOM,
    "tristaini": PropertyType.THREE_ROOM,
    "chetiristaen": PropertyType.FOUR_ROOM,
    "chetiristayn": PropertyType.FOUR_ROOM,
    "chetiristayni": PropertyType.FOUR_ROOM,
    "chetiristaini": PropertyType.FOUR_ROOM,
    "mnogostaen": PropertyType.MULTI_ROOM,
    "mnogostayn": PropertyType.MULTI_ROOM,
    "mnogostayni": PropertyType.MULTI_ROOM,
    "mezonet": PropertyType.MAISONETTE,
    "mezoneti": PropertyType.MAISONETTE,
    "zemedelska": PropertyType.LAND,
    "zemedelski-zemi": PropertyType.LAND,
    "zemya": PropertyType.LAND,
    "kashta": PropertyType.HOUSE,
    "kashti": PropertyType.HOUSE,
    "ofis": PropertyType.OFFICE,
    "atelie": PropertyType.STUDIO_APARTMENT,
    "garazh": PropertyType.GARAGE,
    "parkomyasto": PropertyType.PARKING,
}

CITY_ALIASES: dict[str, City] = {
    # Bulgarian - lowercase for matching
    "софия": City.SOFIA,
    "гр. софия": City.SOFIA,
    "град софия": City.SOFIA,
    "гр.софия": City.SOFIA,
    "пловдив": City.PLOVDIV,
    "гр. пловдив": City.PLOVDIV,
    "град пловдив": City.PLOVDIV,
    "гр.пловдив": City.PLOVDIV,
    "варна": City.VARNA,
    "гр. варна": City.VARNA,
    "град варна": City.VARNA,
    "бургас": City.BURGAS,
    "гр. бургас": City.BURGAS,
    "град бургас": City.BURGAS,
    # Transliterated
    "sofia": City.SOFIA,
    "sofiya": City.SOFIA,
    "grad-sofiya": City.SOFIA,
    "grad-sofia": City.SOFIA,
    "plovdiv": City.PLOVDIV,
    "grad-plovdiv": City.PLOVDIV,
    "varna": City.VARNA,
    "grad-varna": City.VARNA,
    "burgas": City.BURGAS,
    "grad-burgas": City.BURGAS,
}

CURRENCY_ALIASES: dict[str, Currency] = {
    "€": Currency.EUR,
    "eur": Currency.EUR,
    "евро": Currency.EUR,
    "euro": Currency.EUR,
    "лв": Currency.BGN,
    "лв.": Currency.BGN,
    "bgn": Currency.BGN,
    "лева": Currency.BGN,
}

SOFIA_NEIGHBORHOOD_ALIASES: dict[str, SofiaNeighborhood] = {
    # Normalized lowercase Bulgarian -> enum
    "лозенец": SofiaNeighborhood.LOZENETS,
    "кв. лозенец": SofiaNeighborhood.LOZENETS,
    "кв.лозенец": SofiaNeighborhood.LOZENETS,
    "център": SofiaNeighborhood.CENTER,
    "центъра": SofiaNeighborhood.CENTER,
    "иван вазов": SofiaNeighborhood.IVAN_VAZOV,
    "ив. вазов": SofiaNeighborhood.IVAN_VAZOV,
    "ив.вазов": SofiaNeighborhood.IVAN_VAZOV,
    "оборище": SofiaNeighborhood.OBORISHTE,
    "дианабад": SofiaNeighborhood.DIANABAD,
    "изток": SofiaNeighborhood.IZTOK,
    "изгрев": SofiaNeighborhood.IZGREV,
    "яворов": SofiaNeighborhood.YAVOROV,
    "борово": SofiaNeighborhood.BOROVO,
    "гоце делчев": SofiaNeighborhood.GOTSE_DELCHEV,
    "г. делчев": SofiaNeighborhood.GOTSE_DELCHEV,
    "г.делчев": SofiaNeighborhood.GOTSE_DELCHEV,
    "стрелбище": SofiaNeighborhood.STRELBISHTE,
    "хиподрума": SofiaNeighborhood.HIPODRUMA,
    "хладилника": SofiaNeighborhood.HLADILNIKA,
    "пз хладилника": SofiaNeighborhood.HLADILNIKA,
    "белите брези": SofiaNeighborhood.BELITE_BREZI,
    "бели брези": SofiaNeighborhood.BELI_BREZI,
    "витоша": SofiaNeighborhood.VITOSHA,
    "манастирски ливади": SofiaNeighborhood.MANASTIRSKI_LIVADI,
    "студентски град": SofiaNeighborhood.STUDENTSKI_GRAD,
    "студентски": SofiaNeighborhood.STUDENTSKI_GRAD,
    "младост": SofiaNeighborhood.MLADOST,
    "младост 1": SofiaNeighborhood.MLADOST_1,
    "младост 2": SofiaNeighborhood.MLADOST_2,
    "младост 3": SofiaNeighborhood.MLADOST_3,
    "младост 4": SofiaNeighborhood.MLADOST_4,
    "дружба": SofiaNeighborhood.DRUZHBA,
    "дружба 1": SofiaNeighborhood.DRUZHBA_1,
    "дружба 2": SofiaNeighborhood.DRUZHBA_2,
    "люлин": SofiaNeighborhood.LYULIN,
    "надежда": SofiaNeighborhood.NADEZHDA,
    "надежда 1": SofiaNeighborhood.NADEZHDA_1,
    "надежда 2": SofiaNeighborhood.NADEZHDA_2,
    "надежда 3": SofiaNeighborhood.NADEZHDA_3,
    "надежда 4": SofiaNeighborhood.NADEZHDA_4,
    "слатина": SofiaNeighborhood.SLATINA,
    "гео милев": SofiaNeighborhood.GEO_MILEV,
    "редута": SofiaNeighborhood.REDUTA,
    "подуяне": SofiaNeighborhood.PODUYANE,
    "подуене": SofiaNeighborhood.PODUYANE,
    "кръстова вада": SofiaNeighborhood.KRASTOVA_VADA,
    "малинова долина": SofiaNeighborhood.MALINOVA_DOLINA,
    "драгалевци": SofiaNeighborhood.DRAGALEVTSI,
    "бояна": SofiaNeighborhood.BOYANA,
    "симеоново": SofiaNeighborhood.SIMEONOVO,
    "княжево": SofiaNeighborhood.KNYAZHEVO,
    "овча купел": SofiaNeighborhood.OVCHA_KUPEL,
    "красно село": SofiaNeighborhood.KRASNO_SELO,
    "лагера": SofiaNeighborhood.LAGERA,
    "бъкстон": SofiaNeighborhood.BUKSTON,
    "павлово": SofiaNeighborhood.PAVLOVO,
    "хаджи димитър": SofiaNeighborhood.HADJI_DIMITAR,
    "х. димитър": SofiaNeighborhood.HADJI_DIMITAR,
    "левски": SofiaNeighborhood.LEVSKI,
    "левски г": SofiaNeighborhood.LEVSKI_G,
    "левски в": SofiaNeighborhood.LEVSKI_V,
    "сухата река": SofiaNeighborhood.SUHA_REKA,
    "суха река": SofiaNeighborhood.SUHA_REKA,
    "банишора": SofiaNeighborhood.BANISHORA,
    "докторски паметник": SofiaNeighborhood.DOKTORSKI_PAMETNIK,
    "докторски": SofiaNeighborhood.DOKTORSKI_PAMETNIK,
    "дървеница": SofiaNeighborhood.DARVENITSA,
    "мусагеница": SofiaNeighborhood.MUSAGENITSA,
    "медицинска академия": SofiaNeighborhood.MEDITSINSKA_AKADEMIYA,
    "борисова градина": SofiaNeighborhood.BORISOVA_GRADINA,
    "крива река": SofiaNeighborhood.KRIVA_REKA,
    "модерно предградие": SofiaNeighborhood.MODERNO_PREDGRADIE,
    "зона б-5": SofiaNeighborhood.ZONA_B5,
    "зона б5": SofiaNeighborhood.ZONA_B5,
    "зона б-18": SofiaNeighborhood.ZONA_B18,
    "зона б-19": SofiaNeighborhood.ZONA_B19,
    "света троица": SofiaNeighborhood.SVETA_TROITSA,
    "св. троица": SofiaNeighborhood.SVETA_TROITSA,
    "сердика": SofiaNeighborhood.SERDIKA,
    "триъгълника": SofiaNeighborhood.TRIAGALNIKA,
    "полигона": SofiaNeighborhood.POLIGONA,
    "мотописта": SofiaNeighborhood.MOTOPISTA,
    "свобода": SofiaNeighborhood.SVOBODA,
    "толстой": SofiaNeighborhood.TOLSTOY,
    "фондови жилища": SofiaNeighborhood.FONDOVI_ZHILISHTA,
    "западен парк": SofiaNeighborhood.ZAPADEN_PARK,
    "разсадника": SofiaNeighborhood.RAZSADNIKA,
    "карпузица": SofiaNeighborhood.KARPUZITSA,
    "илинден": SofiaNeighborhood.ILINDEN,
    "бенковски": SofiaNeighborhood.BENKOVSKI,
    "орландовци": SofiaNeighborhood.ORLANDOVTSI,
    "малашевци": SofiaNeighborhood.MALASHEVTSI,
    "христо смирненски": SofiaNeighborhood.HRISTO_SMIRNENSKI,
    "хр. смирненски": SofiaNeighborhood.HRISTO_SMIRNENSKI,
    "горна баня": SofiaNeighborhood.GORNA_BANYA,
    "банкя": SofiaNeighborhood.BANKYA,
    "илиянци": SofiaNeighborhood.ILIENTSI,
    "враждебна": SofiaNeighborhood.VRAZHDEBNA,
    "ботунец": SofiaNeighborhood.BOTUNETS,
    "панчарево": SofiaNeighborhood.PANCHAREVO,
    "бистрица": SofiaNeighborhood.BISTRITSA,
    "германа": SofiaNeighborhood.GERMANA,
    # Transliterated versions
    "lozenets": SofiaNeighborhood.LOZENETS,
    "tsentar": SofiaNeighborhood.CENTER,
    "centar": SofiaNeighborhood.CENTER,
    "ivan-vazov": SofiaNeighborhood.IVAN_VAZOV,
    "oborishte": SofiaNeighborhood.OBORISHTE,
    "dianabad": SofiaNeighborhood.DIANABAD,
    "iztok": SofiaNeighborhood.IZTOK,
    "izgrev": SofiaNeighborhood.IZGREV,
    "yavorov": SofiaNeighborhood.YAVOROV,
    "borovo": SofiaNeighborhood.BOROVO,
    "gotse-delchev": SofiaNeighborhood.GOTSE_DELCHEV,
    "strelbishte": SofiaNeighborhood.STRELBISHTE,
    "hipodruma": SofiaNeighborhood.HIPODRUMA,
    "hladilnika": SofiaNeighborhood.HLADILNIKA,
    "vitosha": SofiaNeighborhood.VITOSHA,
    "manastirski-livadi": SofiaNeighborhood.MANASTIRSKI_LIVADI,
    "studentski-grad": SofiaNeighborhood.STUDENTSKI_GRAD,
    "mladost": SofiaNeighborhood.MLADOST,
    "druzhba": SofiaNeighborhood.DRUZHBA,
    "lyulin": SofiaNeighborhood.LYULIN,
    "nadezhda": SofiaNeighborhood.NADEZHDA,
    "slatina": SofiaNeighborhood.SLATINA,
    "geo-milev": SofiaNeighborhood.GEO_MILEV,
    "reduta": SofiaNeighborhood.REDUTA,
    "poduyane": SofiaNeighborhood.PODUYANE,
    "krastova-vada": SofiaNeighborhood.KRASTOVA_VADA,
    "malinova-dolina": SofiaNeighborhood.MALINOVA_DOLINA,
    "dragalevtsi": SofiaNeighborhood.DRAGALEVTSI,
    "boyana": SofiaNeighborhood.BOYANA,
    "simeonovo": SofiaNeighborhood.SIMEONOVO,
    "knyazhevo": SofiaNeighborhood.KNYAZHEVO,
    "ovcha-kupel": SofiaNeighborhood.OVCHA_KUPEL,
    "krasno-selo": SofiaNeighborhood.KRASNO_SELO,
    "lagera": SofiaNeighborhood.LAGERA,
    "bukston": SofiaNeighborhood.BUKSTON,
    "pavlovo": SofiaNeighborhood.PAVLOVO,
    "hadji-dimitar": SofiaNeighborhood.HADJI_DIMITAR,
    "levski": SofiaNeighborhood.LEVSKI,
    "suha-reka": SofiaNeighborhood.SUHA_REKA,
    "banishora": SofiaNeighborhood.BANISHORA,
}

PLOVDIV_NEIGHBORHOOD_ALIASES: dict[str, PlovdivNeighborhood] = {
    # Bulgarian - lowercase
    "център": PlovdivNeighborhood.CENTER,
    "центъра": PlovdivNeighborhood.CENTER,
    "каменица 1": PlovdivNeighborhood.KAMENITSA_1,
    "каменица 2": PlovdivNeighborhood.KAMENITSA_2,
    "каменица": PlovdivNeighborhood.KAMENITSA_1,
    "мараша": PlovdivNeighborhood.MARASHA,
    "младежки хълм": PlovdivNeighborhood.MLADEJKI_HALM,
    "кършияка": PlovdivNeighborhood.KARSHIYAKA,
    "тракия": PlovdivNeighborhood.TRAKIA,
    "смирненски": PlovdivNeighborhood.SMIRNENSKI,
    "христо смирненски": PlovdivNeighborhood.HRISTO_SMIRNENSKI,
    "хр. смирненски": PlovdivNeighborhood.SMIRNENSKI,
    "гребна база": PlovdivNeighborhood.GREBNA_BAZA,
    "въстанически": PlovdivNeighborhood.VASTANICHESKI,
    "христо ботев": PlovdivNeighborhood.HRISTO_BOTEV,
    "хр. ботев": PlovdivNeighborhood.HRISTO_BOTEV,
    "южен": PlovdivNeighborhood.YUZHEN,
    "кючук париж": PlovdivNeighborhood.KYUCHUK_PARIJ,
    "гагарин": PlovdivNeighborhood.GAGARIN,
    "изгрев": PlovdivNeighborhood.IZGREV,
    "захарна фабрика": PlovdivNeighborhood.ZAHARNA_FABRIKA,
    "централна гара": PlovdivNeighborhood.TSENTRALNA_GARA,
    "беломорски": PlovdivNeighborhood.BELOMORSKI,
    "вми": PlovdivNeighborhood.VMI,
    "пещерско шосе": PlovdivNeighborhood.PESHTERSKO_SHOSE,
    "отдих и култура": PlovdivNeighborhood.OTDIH_I_KULTURA,
    "рогошко шосе": PlovdivNeighborhood.ROGOSHKO_SHOSE,
    "бунарджика": PlovdivNeighborhood.BUNARDZHIKA,
    "карловско шосе": PlovdivNeighborhood.KARLOVSKO_SHOSE,
    "тодор каблешков": PlovdivNeighborhood.TODOR_KABLESHKOV,
    "цар симеон": PlovdivNeighborhood.TSAR_SIMEON,
    "индустриална зона": PlovdivNeighborhood.INDUSTRIALNA_ZONA,
    "батак": PlovdivNeighborhood.BATAK,
    "пловдивски университет": PlovdivNeighborhood.PLOVDIVSKI_UNIVERSITET,
    "съдийски": PlovdivNeighborhood.SADIYSKI,
    "капана": PlovdivNeighborhood.KAPANA,
    "филипово": PlovdivNeighborhood.FILIPOVO,
    "прослав": PlovdivNeighborhood.PROSLAV,
    "коматево": PlovdivNeighborhood.KOMATEVO,
    "остромила": PlovdivNeighborhood.OSTROMILA,
    "столипиново": PlovdivNeighborhood.STOLIPINOVO,
    # Transliterated
    "tsentar": PlovdivNeighborhood.CENTER,
    "centar": PlovdivNeighborhood.CENTER,
    "kamenitsa": PlovdivNeighborhood.KAMENITSA_1,
    "marasha": PlovdivNeighborhood.MARASHA,
    "mladejki-halm": PlovdivNeighborhood.MLADEJKI_HALM,
    "karshiyaka": PlovdivNeighborhood.KARSHIYAKA,
    "trakia": PlovdivNeighborhood.TRAKIA,
    "smirnenski": PlovdivNeighborhood.SMIRNENSKI,
    "grebna-baza": PlovdivNeighborhood.GREBNA_BAZA,
    "yuzhen": PlovdivNeighborhood.YUZHEN,
    "gagarin": PlovdivNeighborhood.GAGARIN,
    "izgrev": PlovdivNeighborhood.IZGREV,
    "kapana": PlovdivNeighborhood.KAPANA,
}
